### ISSUE TITLE
vllm批推理错误

### ISSUE THREAD

**Issue by Lebron-James777** [hzauzxb/guidance-ocr#1]
当使用vllm进行批推理时，输出会错误，原因应该是processer类里的self.avi_nodes为全局变量，多batch推理时会导致avi_nodes混乱，请问有解决方法吗

**Comment by hzauzxb** [comment]
> 当使用vllm进行批推理时，输出会错误，原因应该是processer类里的self.avi_nodes为全局变量，多batch推理时会导致avi_nodes混乱，请问有解决方法吗

emmmm，有解决方案，每次调用logit_processor时,  根据上下文计算self.avi_nodes即可。预计这周更新一版吧。

**Comment by hzauzxb** [comment]
bug fixed.  详情见：./examples/qwen2vl/qwen2vl_ocr_vllm.py
